spring:
  cloud:
    gateway:
      routes:
        - id: matchmaking-service
          uri: lb://matchmaking-service
          predicates:
            - Path=/server/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/users/**,/auth/**,/profile